### 设定项目启动端口号
server:
  port: 8888
spring:
  ### 项目应用名
  application:
    name: auto
  ### 数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auto_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    ### druid 配置信息
    druid:
      min-idle: 3
      max-active: 15
      initial-size: 5
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
  ### thymeleaf 相关信息
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/view/
    suffix: .html
  output:
    ansi:
      enabled: always
### Mybatis 相关配置信息
mybatis:
  mapper-locations: classpath:/mapper/*.Mapper.xml
  ### 别名信息
  type-aliases-package: com.weixiao.auto.pojo


